// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bff.proto

package bff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetUserInfoRequest contains the access token for authentication
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_bff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{0}
}

// GetUserInfoResponse contains user information
type GetUserInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sub               string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PreferredUsername string                 `protobuf:"bytes,4,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	GivenName         string                 `protobuf:"bytes,5,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName        string                 `protobuf:"bytes,6,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email             string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_bff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *GetUserInfoResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *GetUserInfoResponse) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// SubscribeEventsRequest specifies the subject pattern to subscribe to
type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject pattern to subscribe to (e.g., "events.*", "notifications.>")
	// This is automatically prefixed with the realm from x-realm metadata
	SubjectPattern string `protobuf:"bytes,1,opt,name=subject_pattern,json=subjectPattern,proto3" json:"subject_pattern,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_bff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeEventsRequest) GetSubjectPattern() string {
	if x != nil {
		return x.SubjectPattern
	}
	return ""
}

// Event represents a single event from the stream
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full subject the event was received on
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// The event payload as bytes
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp when the event was received (RFC3339)
	Timestamp     string `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_bff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// PublishEventRequest contains the event to publish
type PublishEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject suffix to publish to (prefixed with realm automatically)
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// The event payload
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_bff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{4}
}

func (x *PublishEventRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PublishEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PublishEventResponse confirms the publish operation
type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_bff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{5}
}

// RequestReplyRequest contains the request data
type RequestReplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject suffix for the request (prefixed with realm automatically)
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Request payload
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timeout in milliseconds (default: 5000)
	TimeoutMs     int64 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestReplyRequest) Reset() {
	*x = RequestReplyRequest{}
	mi := &file_bff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReplyRequest) ProtoMessage() {}

func (x *RequestReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReplyRequest.ProtoReflect.Descriptor instead.
func (*RequestReplyRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{6}
}

func (x *RequestReplyRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RequestReplyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RequestReplyRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// RequestReplyResponse contains the reply data
type RequestReplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response payload
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestReplyResponse) Reset() {
	*x = RequestReplyResponse{}
	mi := &file_bff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReplyResponse) ProtoMessage() {}

func (x *RequestReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReplyResponse.ProtoReflect.Descriptor instead.
func (*RequestReplyResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{7}
}

func (x *RequestReplyResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_bff_proto protoreflect.FileDescriptor

const file_bff_proto_rawDesc = "" +
	"\n" +
	"\tbff.proto\x12\x06bff.v1\"\x14\n" +
	"\x12GetUserInfoRequest\"\xe7\x01\n" +
	"\x13GetUserInfoResponse\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerified\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12-\n" +
	"\x12preferred_username\x18\x04 \x01(\tR\x11preferredUsername\x12\x1d\n" +
	"\n" +
	"given_name\x18\x05 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x06 \x01(\tR\n" +
	"familyName\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"A\n" +
	"\x16SubscribeEventsRequest\x12'\n" +
	"\x0fsubject_pattern\x18\x01 \x01(\tR\x0esubjectPattern\"S\n" +
	"\x05Event\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"C\n" +
	"\x13PublishEventRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x16\n" +
	"\x14PublishEventResponse\"b\n" +
	"\x13RequestReplyRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"*\n" +
	"\x14RequestReplyResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xae\x02\n" +
	"\n" +
	"BFFService\x12F\n" +
	"\vGetUserInfo\x12\x1a.bff.v1.GetUserInfoRequest\x1a\x1b.bff.v1.GetUserInfoResponse\x12B\n" +
	"\x0fSubscribeEvents\x12\x1e.bff.v1.SubscribeEventsRequest\x1a\r.bff.v1.Event0\x01\x12I\n" +
	"\fPublishEvent\x12\x1b.bff.v1.PublishEventRequest\x1a\x1c.bff.v1.PublishEventResponse\x12I\n" +
	"\fRequestReply\x12\x1b.bff.v1.RequestReplyRequest\x1a\x1c.bff.v1.RequestReplyResponseB,Z*github.com/bluefunda/cai-bff/api/proto/bffb\x06proto3"

var (
	file_bff_proto_rawDescOnce sync.Once
	file_bff_proto_rawDescData []byte
)

func file_bff_proto_rawDescGZIP() []byte {
	file_bff_proto_rawDescOnce.Do(func() {
		file_bff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_proto_rawDesc), len(file_bff_proto_rawDesc)))
	})
	return file_bff_proto_rawDescData
}

var file_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bff_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),     // 0: bff.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),    // 1: bff.v1.GetUserInfoResponse
	(*SubscribeEventsRequest)(nil), // 2: bff.v1.SubscribeEventsRequest
	(*Event)(nil),                  // 3: bff.v1.Event
	(*PublishEventRequest)(nil),    // 4: bff.v1.PublishEventRequest
	(*PublishEventResponse)(nil),   // 5: bff.v1.PublishEventResponse
	(*RequestReplyRequest)(nil),    // 6: bff.v1.RequestReplyRequest
	(*RequestReplyResponse)(nil),   // 7: bff.v1.RequestReplyResponse
}
var file_bff_proto_depIdxs = []int32{
	0, // 0: bff.v1.BFFService.GetUserInfo:input_type -> bff.v1.GetUserInfoRequest
	2, // 1: bff.v1.BFFService.SubscribeEvents:input_type -> bff.v1.SubscribeEventsRequest
	4, // 2: bff.v1.BFFService.PublishEvent:input_type -> bff.v1.PublishEventRequest
	6, // 3: bff.v1.BFFService.RequestReply:input_type -> bff.v1.RequestReplyRequest
	1, // 4: bff.v1.BFFService.GetUserInfo:output_type -> bff.v1.GetUserInfoResponse
	3, // 5: bff.v1.BFFService.SubscribeEvents:output_type -> bff.v1.Event
	5, // 6: bff.v1.BFFService.PublishEvent:output_type -> bff.v1.PublishEventResponse
	7, // 7: bff.v1.BFFService.RequestReply:output_type -> bff.v1.RequestReplyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bff_proto_init() }
func file_bff_proto_init() {
	if File_bff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_proto_rawDesc), len(file_bff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_proto_goTypes,
		DependencyIndexes: file_bff_proto_depIdxs,
		MessageInfos:      file_bff_proto_msgTypes,
	}.Build()
	File_bff_proto = out.File
	file_bff_proto_goTypes = nil
	file_bff_proto_depIdxs = nil
}
