// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: bff.proto

package bff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BFFService_GetUserInfo_FullMethodName              = "/bff.v1.BFFService/GetUserInfo"
	BFFService_SubscribeEvents_FullMethodName          = "/bff.v1.BFFService/SubscribeEvents"
	BFFService_PublishEvent_FullMethodName             = "/bff.v1.BFFService/PublishEvent"
	BFFService_RequestReply_FullMethodName             = "/bff.v1.BFFService/RequestReply"
	BFFService_ListChangeRequests_FullMethodName       = "/bff.v1.BFFService/ListChangeRequests"
	BFFService_GetChangeRequest_FullMethodName         = "/bff.v1.BFFService/GetChangeRequest"
	BFFService_CreateChangeRequest_FullMethodName      = "/bff.v1.BFFService/CreateChangeRequest"
	BFFService_UpdateChangeRequest_FullMethodName      = "/bff.v1.BFFService/UpdateChangeRequest"
	BFFService_DeleteChangeRequest_FullMethodName      = "/bff.v1.BFFService/DeleteChangeRequest"
	BFFService_UpdateChangeRequestStage_FullMethodName = "/bff.v1.BFFService/UpdateChangeRequestStage"
	BFFService_ListComments_FullMethodName             = "/bff.v1.BFFService/ListComments"
	BFFService_AddComment_FullMethodName               = "/bff.v1.BFFService/AddComment"
	BFFService_UpdateComment_FullMethodName            = "/bff.v1.BFFService/UpdateComment"
	BFFService_DeleteComment_FullMethodName            = "/bff.v1.BFFService/DeleteComment"
)

// BFFServiceClient is the client API for BFFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BFFService provides backend-for-frontend operations for the TRM platform.
type BFFServiceClient interface {
	// User
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// Events (message bus — CLI never hits NATS directly)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error)
	RequestReply(ctx context.Context, in *RequestReplyRequest, opts ...grpc.CallOption) (*RequestReplyResponse, error)
	// Change Requests
	ListChangeRequests(ctx context.Context, in *ListChangeRequestsRequest, opts ...grpc.CallOption) (*ListChangeRequestsResponse, error)
	GetChangeRequest(ctx context.Context, in *GetChangeRequestRequest, opts ...grpc.CallOption) (*GetChangeRequestResponse, error)
	CreateChangeRequest(ctx context.Context, in *CreateChangeRequestRequest, opts ...grpc.CallOption) (*CreateChangeRequestResponse, error)
	UpdateChangeRequest(ctx context.Context, in *UpdateChangeRequestRequest, opts ...grpc.CallOption) (*UpdateChangeRequestResponse, error)
	DeleteChangeRequest(ctx context.Context, in *DeleteChangeRequestRequest, opts ...grpc.CallOption) (*DeleteChangeRequestResponse, error)
	UpdateChangeRequestStage(ctx context.Context, in *UpdateChangeRequestStageRequest, opts ...grpc.CallOption) (*UpdateChangeRequestStageResponse, error)
	// Comments
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*AddCommentResponse, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error)
}

type bFFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBFFServiceClient(cc grpc.ClientConnInterface) BFFServiceClient {
	return &bFFServiceClient{cc}
}

func (c *bFFServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, BFFService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BFFService_ServiceDesc.Streams[0], BFFService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFFService_SubscribeEventsClient = grpc.ServerStreamingClient[Event]

func (c *bFFServiceClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*PublishEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishEventResponse)
	err := c.cc.Invoke(ctx, BFFService_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) RequestReply(ctx context.Context, in *RequestReplyRequest, opts ...grpc.CallOption) (*RequestReplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestReplyResponse)
	err := c.cc.Invoke(ctx, BFFService_RequestReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) ListChangeRequests(ctx context.Context, in *ListChangeRequestsRequest, opts ...grpc.CallOption) (*ListChangeRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChangeRequestsResponse)
	err := c.cc.Invoke(ctx, BFFService_ListChangeRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetChangeRequest(ctx context.Context, in *GetChangeRequestRequest, opts ...grpc.CallOption) (*GetChangeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangeRequestResponse)
	err := c.cc.Invoke(ctx, BFFService_GetChangeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) CreateChangeRequest(ctx context.Context, in *CreateChangeRequestRequest, opts ...grpc.CallOption) (*CreateChangeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChangeRequestResponse)
	err := c.cc.Invoke(ctx, BFFService_CreateChangeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) UpdateChangeRequest(ctx context.Context, in *UpdateChangeRequestRequest, opts ...grpc.CallOption) (*UpdateChangeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChangeRequestResponse)
	err := c.cc.Invoke(ctx, BFFService_UpdateChangeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) DeleteChangeRequest(ctx context.Context, in *DeleteChangeRequestRequest, opts ...grpc.CallOption) (*DeleteChangeRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChangeRequestResponse)
	err := c.cc.Invoke(ctx, BFFService_DeleteChangeRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) UpdateChangeRequestStage(ctx context.Context, in *UpdateChangeRequestStageRequest, opts ...grpc.CallOption) (*UpdateChangeRequestStageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChangeRequestStageResponse)
	err := c.cc.Invoke(ctx, BFFService_UpdateChangeRequestStage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, BFFService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*AddCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCommentResponse)
	err := c.cc.Invoke(ctx, BFFService_AddComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, BFFService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*DeleteCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommentResponse)
	err := c.cc.Invoke(ctx, BFFService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BFFServiceServer is the server API for BFFService service.
// All implementations must embed UnimplementedBFFServiceServer
// for forward compatibility.
//
// BFFService provides backend-for-frontend operations for the TRM platform.
type BFFServiceServer interface {
	// User
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// Events (message bus — CLI never hits NATS directly)
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error
	PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error)
	RequestReply(context.Context, *RequestReplyRequest) (*RequestReplyResponse, error)
	// Change Requests
	ListChangeRequests(context.Context, *ListChangeRequestsRequest) (*ListChangeRequestsResponse, error)
	GetChangeRequest(context.Context, *GetChangeRequestRequest) (*GetChangeRequestResponse, error)
	CreateChangeRequest(context.Context, *CreateChangeRequestRequest) (*CreateChangeRequestResponse, error)
	UpdateChangeRequest(context.Context, *UpdateChangeRequestRequest) (*UpdateChangeRequestResponse, error)
	DeleteChangeRequest(context.Context, *DeleteChangeRequestRequest) (*DeleteChangeRequestResponse, error)
	UpdateChangeRequestStage(context.Context, *UpdateChangeRequestStageRequest) (*UpdateChangeRequestStageResponse, error)
	// Comments
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error)
	mustEmbedUnimplementedBFFServiceServer()
}

// UnimplementedBFFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBFFServiceServer struct{}

func (UnimplementedBFFServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedBFFServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedBFFServiceServer) PublishEvent(context.Context, *PublishEventRequest) (*PublishEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedBFFServiceServer) RequestReply(context.Context, *RequestReplyRequest) (*RequestReplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestReply not implemented")
}
func (UnimplementedBFFServiceServer) ListChangeRequests(context.Context, *ListChangeRequestsRequest) (*ListChangeRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChangeRequests not implemented")
}
func (UnimplementedBFFServiceServer) GetChangeRequest(context.Context, *GetChangeRequestRequest) (*GetChangeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChangeRequest not implemented")
}
func (UnimplementedBFFServiceServer) CreateChangeRequest(context.Context, *CreateChangeRequestRequest) (*CreateChangeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChangeRequest not implemented")
}
func (UnimplementedBFFServiceServer) UpdateChangeRequest(context.Context, *UpdateChangeRequestRequest) (*UpdateChangeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChangeRequest not implemented")
}
func (UnimplementedBFFServiceServer) DeleteChangeRequest(context.Context, *DeleteChangeRequestRequest) (*DeleteChangeRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChangeRequest not implemented")
}
func (UnimplementedBFFServiceServer) UpdateChangeRequestStage(context.Context, *UpdateChangeRequestStageRequest) (*UpdateChangeRequestStageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChangeRequestStage not implemented")
}
func (UnimplementedBFFServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedBFFServiceServer) AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedBFFServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedBFFServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*DeleteCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedBFFServiceServer) mustEmbedUnimplementedBFFServiceServer() {}
func (UnimplementedBFFServiceServer) testEmbeddedByValue()                    {}

// UnsafeBFFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFFServiceServer will
// result in compilation errors.
type UnsafeBFFServiceServer interface {
	mustEmbedUnimplementedBFFServiceServer()
}

func RegisterBFFServiceServer(s grpc.ServiceRegistrar, srv BFFServiceServer) {
	// If the following call panics, it indicates UnimplementedBFFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BFFService_ServiceDesc, srv)
}

func _BFFService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BFFServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFFService_SubscribeEventsServer = grpc.ServerStreamingServer[Event]

func _BFFService_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_RequestReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).RequestReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_RequestReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).RequestReply(ctx, req.(*RequestReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_ListChangeRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChangeRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).ListChangeRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_ListChangeRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).ListChangeRequests(ctx, req.(*ListChangeRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetChangeRequest(ctx, req.(*GetChangeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_CreateChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChangeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).CreateChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_CreateChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).CreateChangeRequest(ctx, req.(*CreateChangeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_UpdateChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChangeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).UpdateChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_UpdateChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).UpdateChangeRequest(ctx, req.(*UpdateChangeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_DeleteChangeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChangeRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).DeleteChangeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_DeleteChangeRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).DeleteChangeRequest(ctx, req.(*DeleteChangeRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_UpdateChangeRequestStage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChangeRequestStageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).UpdateChangeRequestStage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_UpdateChangeRequestStage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).UpdateChangeRequestStage(ctx, req.(*UpdateChangeRequestStageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_AddComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).AddComment(ctx, req.(*AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BFFService_ServiceDesc is the grpc.ServiceDesc for BFFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bff.v1.BFFService",
	HandlerType: (*BFFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _BFFService_GetUserInfo_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _BFFService_PublishEvent_Handler,
		},
		{
			MethodName: "RequestReply",
			Handler:    _BFFService_RequestReply_Handler,
		},
		{
			MethodName: "ListChangeRequests",
			Handler:    _BFFService_ListChangeRequests_Handler,
		},
		{
			MethodName: "GetChangeRequest",
			Handler:    _BFFService_GetChangeRequest_Handler,
		},
		{
			MethodName: "CreateChangeRequest",
			Handler:    _BFFService_CreateChangeRequest_Handler,
		},
		{
			MethodName: "UpdateChangeRequest",
			Handler:    _BFFService_UpdateChangeRequest_Handler,
		},
		{
			MethodName: "DeleteChangeRequest",
			Handler:    _BFFService_DeleteChangeRequest_Handler,
		},
		{
			MethodName: "UpdateChangeRequestStage",
			Handler:    _BFFService_UpdateChangeRequestStage_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _BFFService_ListComments_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _BFFService_AddComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _BFFService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _BFFService_DeleteComment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _BFFService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bff.proto",
}
